### ISSUE TITLE
Merge xml2kinto and kinto2xml

### ISSUE THREAD

**Issue by Natim** [mozilla-services/xml2kinto#36]
Now that xml2kinto is in good shape, it would be great to add the kinto2xml command in the same repository.

**Comment by magopian** [comment]
very good idea, and i'd like to also merge amo-blocklist-ui, so we have the schema in the same place. I think it would make sense.

**Comment by Natim** [comment]
Well for me amo-blocklist-ui is a javascript project so I am not a big fan of merging it here.
Plus while deploying the amo-blocklist-ui website we are not likely to want to deploy the xml2kinto package. And when we want to install xml2kinto we are not likely to want to deploy the amo-blocklist-ui.

**Comment by magopian** [comment]
Makes sense, in a way. But if you think about it, those three projects are all linked to the amo-blocklist, be it the import script, the export script, or the admin interface.

I have no strong opinion here.

**Comment by Natim** [comment]
Since we are not using xml2kinto for importing data from AMO anymore, we do not need to do that merge anymore.

kinto2xml already ship with the new importation flow.
